name: Update README with Blueprints Table

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  update-readmes:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Checkout .github repository
        uses: actions/checkout@v4
        with:
          repository: krateoplatformops-blueprints/.github
          ref: main
          path: dotgithub

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Generate Blueprints Table
        id: generate
        run: |
          BLUEPRINTS_TABLE=$(yq eval -o=json '.entries' gh-pages/index.yaml | jq -r '
            to_entries[] 
            | .value[] 
            | [
                .name,
                .version,
                (.keywords[0] // "unknown"),
                (.sources[0] // "n/a"),
                (.description // "n/a")
              ] 
            | @tsv' | awk -F '\t' 'BEGIN {
                print "| Blueprint Name | Blueprint Version | Blueprint Category | Blueprint Repository | Blueprint Description |";
                print "|----------------|-------------------|---------------------|-----------------------|------------------------|";
              } {
                repo_url = $4;
                version_url = repo_url "/tree/" $2;
                printf("| %s | [%s](%s) | %s | [%s](%s) | %s |\n", $1, $2, version_url, $3, repo_url, repo_url, $5);
              }')

          echo "BLUEPRINTS_TABLE<<EOF" >> $GITHUB_ENV
          echo "$BLUEPRINTS_TABLE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update main/README.md
        run: |
          cd main
          awk -v table="${BLUEPRINTS_TABLE}" '
            BEGIN { in_section = 0 }
            /<!-- Available Blueprints START -->/ { print; print table; in_section = 1; next }
            /<!-- Available Blueprints END -->/ { in_section = 0 }
            !in_section
          ' README.md > README.new.md && mv README.new.md README.md

      - name: Update .github/profile/README.md
        run: |
          cd dotgithub/profile
          awk -v table="${BLUEPRINTS_TABLE}" '
            BEGIN { in_section = 0 }
            /<!-- Available Blueprints START -->/ { print; print table; in_section = 1; next }
            /<!-- Available Blueprints END -->/ { in_section = 0 }
            !in_section
          ' README.md > README.new.md && mv README.new.md README.md

      - name: Commit and push to main repo
        run: |
          cd main
          git config user.name "krateo-bot"
          git config user.email "bot@krateo.io"
          git add README.md
          git commit -m "docs: update README with latest blueprints [automated]" || echo "No changes"
          git push origin main

      - name: Commit and push to .github repo
        run: |
          cd dotgithub
          git config user.name "krateo-bot"
          git config user.email "bot@krateo.io"
          git add profile/README.md
          git commit -m "docs: update profile README with blueprint index [automated]" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/krateoplatformops-blueprints/.github.git main
